services:
  db:
    image: mysql:8.0.32
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: sandbox_db
      MYSQL_USER: sandbox_user
      MYSQL_PASSWORD: sandbox_password
    #volumes:
      # Uncomment for persistent storage
      #- ./db/data:/var/lib/mysql
      # Uncomment to pass custom MySQL config
      #- ./db/conf:/etc/mysql/conf.d