apiVersion: v1
kind: LimitRange
metadata:
  name: default-limit-range
spec:
  limits:
    - type: Container
      default:
        memory: 500Mi
        cpu: 200m
      defaultRequest:
        memory: 200Mi
        cpu: 100m